# Generated by Django 4.2.7 on 2023-12-05 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_alter_cafe_mesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAdicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('AC', 'Adiciona Chocolate'), ('AO', 'Adiciona Ovomaltine'), ('AL', 'Adiciona Leite'), ('AM', 'Adiciona Amendoim')], max_length=3)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('data_inicio', models.DateField(null=True)),
                ('hora_entrega', models.DateTimeField(null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('protecolo', models.CharField(blank=True, max_length=32, null=True)),
                ('categoria_adicao', models.ManyToManyField(to='servicos.categoriaadicao')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
            ],
        ),
    ]
