# Generated by Django 4.2.7 on 2023-12-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='protecolo',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
