# Generated by Django 4.2.7 on 2023-11-24 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='cafe',
            new_name='pedido',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='consumo',
        ),
    ]
